title: Dr. Ayman Elgharabawy
logo: Ayman_ANU_small.jpg
description: Ayman postdoctoral fellow at Biological Data Science Institute (BDSI) and a visitor Scientist at SCIRO F&AG. dep.   Ayman received his  Ph.D. (2022) from the School of Computer Science, Faculty of Engineering and Information Technology, University of Technology Sydney (UTS). Australia. Ayman Finished his Bachelor's and Master's degree in the Biomedical Engineering Dep. Faculty of Engineering, Cairo University, Egypt. 
Ayman has multiple disciplinary, academic, and professional areas.
 His research focuses on implementing Machine learning algorithms for  Biosignal, Bioinformatics, and Preference Learning using Neural networks to solve different bioinformatics, image processing, and Brain-Computer Interfaces (BCI) problems. 
 Ayman has 14+ years of experience as a programmer, software designer, and technical and solution architect in different companies (HP, CGI-Logica, Vodafone).
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
